name: aTeas
favicon: null
layout_spectrum: 0
typography_spectrum: 0.77637
title: aTeas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afd994'
  brandStrength: 0.6875
  lightness: 0.9507684845011681
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
