name: aTeaSaloon
favicon: null
layout_spectrum: 0.7423238174524158
typography_spectrum: 0.05683929962106049
title: a Tea Saloon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.01120719755999744
  lightness: 0.9507684845011681
  saturation: 0.20385150774382055
  rhythmicContrast: 0.5357751238625497
purpose: []
