typography_spectrum: 0.4825880783610046
color:
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
  brandStrength: 0.022048987913876772
  lightness: 0.6721573325339705
  saturation: 0.8644008347764611
  rhythmicContrast: 0.22931991633959115
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6414808321278542
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Thom LaFay
name: tèVita
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Info
    id: a08d3ca7-e52e-4d50-a9e0-150bc1c29da1
    type: content
  - name: Sui Generis
    id: 6a047502-faea-4254-bdd3-976a9a4f8b56
    type: content
  - name: Bloom
    id: b9c43933-5b1b-4eea-b0e0-dec678c6fbe0
    type: content
  - name: Prime
    id: fcad7321-a625-4e10-8178-0836d17899ad
    type: content
  - name: Pristine
    id: ab67dc7e-fd0f-4e01-8bc9-6b47db844d28
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: téVita
purpose: []
