typography_spectrum: 0.32280511828139424
color:
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  brandStrength: 0.13428691495209932
  lightness: 0.10931874183006585
  saturation: 0.9677282427437603
  rhythmicContrast: 0.15979467518627644
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.203570154029876
analytics:
  google: null
  facebook: null
  twitter: null
name: aTeas
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: aTeas
purpose: []
